// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeMTG.API.Database;

#nullable disable

namespace SeMTG.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425220442_AddQdrantInfo")]
    partial class AddQdrantInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeMTG.API.Models.ImageUris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtCrop")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "art_crop");

                    b.Property<string>("BorderCrop")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "border_crop");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "large");

                    b.Property<string>("Normal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "normal");

                    b.Property<string>("Png")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "png");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "small");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallCardObjectId")
                        .IsUnique();

                    b.ToTable("ImageUris");

                    b.HasAnnotation("Relational:JsonPropertyName", "image_uris");
                });

            modelBuilder.Entity("SeMTG.API.Models.Legalities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alchemy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "alchemy");

                    b.Property<string>("Brawl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "brawl");

                    b.Property<string>("Commander")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "commander");

                    b.Property<string>("Duel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "duel");

                    b.Property<string>("Explorer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "explorer");

                    b.Property<string>("Future")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "future");

                    b.Property<string>("Gladiator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "gladiator");

                    b.Property<string>("Historic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "historic");

                    b.Property<string>("Legacy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "legacy");

                    b.Property<string>("Modern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "modern");

                    b.Property<string>("Oathbreaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "oathbreaker");

                    b.Property<string>("Oldschool")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "oldschool");

                    b.Property<string>("Pauper")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "pauper");

                    b.Property<string>("Paupercommander")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "paupercommander");

                    b.Property<string>("Penny")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "penny");

                    b.Property<string>("Pioneer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "pioneer");

                    b.Property<string>("Predh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "predh");

                    b.Property<string>("Premodern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "premodern");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "standard");

                    b.Property<string>("Standardbrawl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "standardbrawl");

                    b.Property<string>("Timeless")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "timeless");

                    b.Property<string>("Vintage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "vintage");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallCardObjectId")
                        .IsUnique();

                    b.ToTable("Legalities");

                    b.HasAnnotation("Relational:JsonPropertyName", "legalities");
                });

            modelBuilder.Entity("SeMTG.API.Models.Prices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Eur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "eur");

                    b.Property<string>("EurFoil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "eur_foil");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tix");

                    b.Property<string>("Usd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "usd");

                    b.Property<string>("UsdEtched")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "usd_etched");

                    b.Property<string>("UsdFoil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "usd_foil");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallCardObjectId")
                        .IsUnique();

                    b.ToTable("Prices");

                    b.HasAnnotation("Relational:JsonPropertyName", "prices");
                });

            modelBuilder.Entity("SeMTG.API.Models.PurchaseUris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cardhoarder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "cardhoarder");

                    b.Property<string>("Cardmarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "cardmarket");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tcgplayer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tcgplayer");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallCardObjectId")
                        .IsUnique();

                    b.ToTable("PurchaseUris");

                    b.HasAnnotation("Relational:JsonPropertyName", "purchase_uris");
                });

            modelBuilder.Entity("SeMTG.API.Models.QdrantInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("Id");

                    b.ToTable("QdrantInfo");
                });

            modelBuilder.Entity("SeMTG.API.Models.RelatedUris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Edhrec")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "edhrec");

                    b.Property<string>("Gatherer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "gatherer");

                    b.Property<Guid>("ScryfallCardObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TcgplayerInfiniteArticles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tcgplayer_infinite_articles");

                    b.Property<string>("TcgplayerInfiniteDecks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tcgplayer_infinite_decks");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallCardObjectId")
                        .IsUnique();

                    b.ToTable("RelatedUris");

                    b.HasAnnotation("Relational:JsonPropertyName", "related_uris");
                });

            modelBuilder.Entity("SeMTG.API.Models.ScryfallCardObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int?>("ArenaId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "arena_id");

                    b.Property<string>("Artist")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "artist");

                    b.PrimitiveCollection<List<string>>("ArtistIds")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "artist_ids");

                    b.Property<bool?>("Booster")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "booster");

                    b.Property<string>("BorderColor")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "border_color");

                    b.Property<string>("CardBackId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "card_back_id");

                    b.Property<double?>("Cmc")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "cmc");

                    b.Property<string>("CollectorNumber")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "collector_number");

                    b.PrimitiveCollection<List<string>>("ColorIdentity")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "color_identity");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "colors");

                    b.Property<bool?>("Digital")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "digital");

                    b.PrimitiveCollection<List<string>>("Finishes")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "finishes");

                    b.Property<bool?>("Foil")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "foil");

                    b.Property<string>("Frame")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "frame");

                    b.Property<bool?>("FullArt")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "full_art");

                    b.Property<bool?>("GameChanger")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "game_changer");

                    b.PrimitiveCollection<List<string>>("Games")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "games");

                    b.Property<bool?>("HighresImage")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "highres_image");

                    b.Property<string>("IllustrationId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "illustration_id");

                    b.Property<string>("ImageStatus")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image_status");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "keywords");

                    b.Property<string>("Lang")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "lang");

                    b.Property<string>("Layout")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "layout");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "mana_cost");

                    b.Property<int?>("MtgoId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "mtgo_id");

                    b.PrimitiveCollection<List<int?>>("MultiverseIds")
                        .HasColumnType("integer[]")
                        .HasAnnotation("Relational:JsonPropertyName", "multiverse_ids");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<bool?>("Nonfoil")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "nonfoil");

                    b.Property<string>("Object")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "object");

                    b.Property<string>("OracleId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "oracle_id");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "oracle_text");

                    b.Property<bool?>("Oversized")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "oversized");

                    b.Property<string>("PrintsSearchUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "prints_search_uri");

                    b.PrimitiveCollection<List<string>>("ProducedMana")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "produced_mana");

                    b.Property<bool?>("Promo")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "promo");

                    b.Property<string>("Rarity")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "rarity");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "released_at");

                    b.Property<bool?>("Reprint")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "reprint");

                    b.Property<bool?>("Reserved")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "reserved");

                    b.Property<string>("RulingsUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "rulings_uri");

                    b.Property<string>("ScryfallSetUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "scryfall_set_uri");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "scryfall_uri");

                    b.Property<string>("Set")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set");

                    b.Property<string>("SetId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set_id");

                    b.Property<string>("SetName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set_name");

                    b.Property<string>("SetSearchUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set_search_uri");

                    b.Property<string>("SetType")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set_type");

                    b.Property<string>("SetUri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "set_uri");

                    b.Property<bool?>("StorySpotlight")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "story_spotlight");

                    b.Property<int?>("TcgplayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "tcgplayer_id");

                    b.Property<bool?>("Textless")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "textless");

                    b.Property<string>("TypeLine")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "type_line");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "uri");

                    b.Property<bool?>("Variation")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "variation");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OracleText");

                    b.HasIndex("TypeLine");

                    b.ToTable("ScryfallCards");
                });

            modelBuilder.Entity("SeMTG.API.Models.ImageUris", b =>
                {
                    b.HasOne("SeMTG.API.Models.ScryfallCardObject", null)
                        .WithOne("ImageUris")
                        .HasForeignKey("SeMTG.API.Models.ImageUris", "ScryfallCardObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeMTG.API.Models.Legalities", b =>
                {
                    b.HasOne("SeMTG.API.Models.ScryfallCardObject", null)
                        .WithOne("Legalities")
                        .HasForeignKey("SeMTG.API.Models.Legalities", "ScryfallCardObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeMTG.API.Models.Prices", b =>
                {
                    b.HasOne("SeMTG.API.Models.ScryfallCardObject", null)
                        .WithOne("Prices")
                        .HasForeignKey("SeMTG.API.Models.Prices", "ScryfallCardObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeMTG.API.Models.PurchaseUris", b =>
                {
                    b.HasOne("SeMTG.API.Models.ScryfallCardObject", null)
                        .WithOne("PurchaseUris")
                        .HasForeignKey("SeMTG.API.Models.PurchaseUris", "ScryfallCardObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeMTG.API.Models.RelatedUris", b =>
                {
                    b.HasOne("SeMTG.API.Models.ScryfallCardObject", null)
                        .WithOne("RelatedUris")
                        .HasForeignKey("SeMTG.API.Models.RelatedUris", "ScryfallCardObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeMTG.API.Models.ScryfallCardObject", b =>
                {
                    b.Navigation("ImageUris");

                    b.Navigation("Legalities");

                    b.Navigation("Prices");

                    b.Navigation("PurchaseUris");

                    b.Navigation("RelatedUris");
                });
#pragma warning restore 612, 618
        }
    }
}
